# PrintScreen uses flameshot
bindsym Print exec --no-startup-id flameshot screen
bindsym Shift+Print exec --no-startup-id flameshot gui

# numpad default on
exec --no-startup-id xdotool key --clearmodifiers Num_Lock

# swap ESC and Caps Lock
exec_always --no-startup-id sleep 1; setxkbmap -option "caps:swapescape"

# Auto start keeper
exec --no-startup-id i3-msg 'workspace 10; exec keeperpasswordmanager
