# unbindsym $mod+f
# bindsym $mod+f exec ~/dotfiles/config/regolith3/sway-maximize.sh

bindsym Print exec --no-startup-id XDG_CURRENT_DESKTOP=sway flameshot screen --raw | wl-copy
bindsym Shift+Print exec --no-startup-id env XDG_CURRENT_DESKTOP=sway QT_QPA_PLATFORM=wayland flameshot gui --raw | wl-copy

# numpad on and swap ESC and Caps Lock
input * {
    xkb_numlock enabled
	xkb_options caps:swapescape
}

# since nagbar is not automatically focused, create custom shutdown menu:
unbindsym $mod+Shift+p
unbindsym $mod+Shift+b
bindsym $mod+Shift+p exec sh -c 'printf "Yes\nCancel\n" | wofi --dmenu --prompt "Shutdown?" --lines 2 --width 200 | grep -qx Yes && systemctl poweroff'
bindsym $mod+Shift+b exec sh -c 'printf "Yes\nCancel\n" | wofi --dmenu --prompt "Reboot?" --lines 2 --width 200 | grep -qx Yes && systemctl reboot'
