# move focused workspace between monitors
bindsym $mod+comma move workspace to output next

# numpad default on
exec --no-startup-id xdotool key --clearmodifiers Num_Lock

# swap ESC and Caps Lock
exec_always --no-startup-id setxkbmap -option "caps:swapescape"
